### ISSUE TITLE
Difference with AzCopy V10

### ISSUE THREAD

**Issue by BossensM** [Azure/blobxfer#99]
I was wondering, Microsoft recently released V10 of AzCopy (https://github.com/Azure/azure-storage-azcopy). What exactly is the difference between blobxfer and AzCopy, and which one is the recommended one to use? 

I am looking specifically for performance on uploading/downloading a lot of small files. According to this announcement, https://azure.microsoft.com/en-us/blog/azcopy-support-in-azure-storage-explorer-now-available-in-public-preview/, AzCopy seems to be very fast but it is not clear if Azure Storage Explorer was previously based on blobxfer.

**Comment by alfpark** [comment]
As a CLI tool, they have similar feature sets. You will need to evaluate to see which tool is right for your scenario as each will have different behavioral and tuning options available.

Azure Storage Explorer does not use blobxfer.

**Comment by ypresto** [comment]
I personally prefer AzCopy over blobxfer, because:

- [AzCopy seems to index files faster for many small files](https://azure.microsoft.com/en-us/blog/azcopy-support-in-azure-storage-explorer-now-available-in-public-preview/), while blobxfer generates one API call per file for existence check and is much slower.
- AzCopy tolerate errors while blobxfer does not (we got uncaught error on a test file with CRLF in its name).

**Comment by alfpark** [comment]
@ypresto, thanks for bringing up these issues.

> AzCopy seems to index files faster for many small files, while blobxfer generates one API call per file for existence check and is much slower.

There are some backlogged optimizations that can be done here. One would dramatically improve performance in the default `overwrite` case (I'll make the change in the next version). To honor `skip_on` options, fundamentally, each object must be point queried (as far as I know).

> AzCopy tolerate errors while blobxfer does not (we got uncaught error on a test file with CRLF in its name)

This would appear to be a bug - opening an issue for this would be appreciated rather than categorizing this as a disadvantage.
